import assert from 'node:assert/strict';
import test from 'node:test';
import { createServer } from 'node:http';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { NextRequest } from 'next/server';
import { createAdminSession, logoutAdmin } from '../src/core/auth';
import { executeSceneLibraryCommand } from '../server/scene/sceneLibrary';
import { listPublicWorlds, readWorldAccess, saveWorldAccess } from '../server/scene/publicWorlds';
import { persistedSceneFilePath } from '../server/scene/persistSceneDocumentV0_1';
import { loadContentManifestOrThrow } from '../server/content/loadContentManifest';
import { tryHandleGameMonitorRequest } from '../server/metrics/gameMonitorHttp';
import { GET as listWorlds } from '../src/app/api/public/worlds/route';
import { POST as changeAccess, GET as readAccess } from '../src/app/api/admin/scene-authoring/access/route';
import { POST as joinTicket } from '../src/app/api/game/join-ticket/route';
import { NexusWorldRoom } from '../server/rooms/NexusWorldRoom';
import type { Client } from 'colyseus';
import { parseSceneDocumentV0_1 } from '@nexusworld3d/content-schema';
import playable from '../content/scenes/playable.v0_1.json';

test('admin publication/access, public catalog, guest tickets and server admission agree', async () => {
  const dir = mkdtempSync(join(tmpdir(), 'nexus-public-worlds-'));
  const keys = ['NEXUS_SCENE_PERSIST_DIR', 'NEXUS_GAME_MONITOR_SECRET', 'NEXUS_GAME_MONITOR_URL', 'AUTH_SECRET', 'NEXTAUTH_SECRET', 'NEXUS_SCENE_LOAD_PERSISTED'] as const;
  const previous = keys.map(key => process.env[key]);
  process.env.NEXUS_SCENE_PERSIST_DIR = dir; process.env.NEXUS_GAME_MONITOR_SECRET = 'public-world-test';
  delete process.env.AUTH_SECRET; delete process.env.NEXTAUTH_SECRET; process.env.NEXUS_SCENE_LOAD_PERSISTED = '0';
  loadContentManifestOrThrow();
  const session = createAdminSession('world-test');
  const server = createServer((req, res) => { void tryHandleGameMonitorRequest(req, res).then(handled => { if (!handled) { res.writeHead(404); res.end(); } }); });
  try {
    await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
    const address = server.address(); assert.ok(address && typeof address !== 'string');
    process.env.NEXUS_GAME_MONITOR_URL = `http://127.0.0.1:${address.port}`;
    const worldId = 'web-created';
    const document = parseSceneDocumentV0_1({ ...playable, worldId });
    const access = { worldId, name: 'Web created', public: true };
    assert.throws(() => saveWorldAccess(access), /publish_valid_scene_first/);
    const state = executeSceneLibraryCommand({ action: 'publish', worldId, document, expectedRevision: null });
    assert.deepEqual(listPublicWorlds(), [], 'publication alone does not expose the world');
    const url = 'http://localhost/api/admin/scene-authoring/access';
    const headers = { cookie: `admin_session=${session}`, origin: 'http://localhost' };
    assert.equal((await changeAccess(new NextRequest(url, { method: 'POST', body: JSON.stringify(access) }))).status, 401);
    assert.equal((await changeAccess(new NextRequest(url, { method: 'POST', headers: { ...headers, origin: 'https://foreign.invalid' }, body: JSON.stringify(access) }))).status, 403);
    assert.equal((await changeAccess(new NextRequest(url, { method: 'POST', headers, body: JSON.stringify(access) }))).status, 200);
    const response = await listWorlds(new NextRequest('http://localhost/api/public/worlds'));
    assert.equal((await response.json()).worlds[0].worldId, worldId);
    assert.equal((await readAccess(new NextRequest(`${url}?worldId=${worldId}`, { headers }))).status, 200);
    assert.equal(readWorldAccess(worldId)?.public, true);
    const ticket = await joinTicket(new Request('http://localhost/api/game/join-ticket', { method: 'POST', body: JSON.stringify({ roomName: 'nexus-world', worldId }) }));
    assert.equal(ticket.status, 200);
    assert.deepEqual(await ticket.json(), { ticket: null, worldId });
    const room = new NexusWorldRoom(); room.roomName = 'nexus-world';
    assert.equal(room.onAuth({ sessionId: 'guest' } as Client, { worldId }).worldId, worldId);
    assert.deepEqual((room as unknown as { sceneDocumentV0_1: unknown }).sceneDocumentV0_1, document, 'public world loads even when legacy auto-load switch is disabled');
    const bad = structuredClone(document); bad.entities[0].components.push({ type: 'game:unknown', props: {} });
    assert.throws(() => executeSceneLibraryCommand({ action: 'publish', worldId, document: bad, expectedRevision: state.publishedRevision }), /unsupported_public_component/);
    saveWorldAccess({ ...access, public: false });
    assert.deepEqual(listPublicWorlds(), []);
    assert.throws(() => room.onAuth({ sessionId: 'denied' } as Client, { worldId }), /not available/);
    assert.equal((await joinTicket(new Request('http://localhost/api/game/join-ticket', { method: 'POST', body: JSON.stringify({ roomName: 'nexus-world', worldId }) }))).status, 404);
    assert.throws(() => saveWorldAccess({ ...access, worldId: '../../escape' }));
    saveWorldAccess(access);
    writeFileSync(persistedSceneFilePath(worldId), '{broken');
    assert.deepEqual(listPublicWorlds(), [], 'corrupt published scenes fail closed');
  } finally {
    logoutAdmin(session); await new Promise<void>(resolve => server.close(() => resolve()));
    keys.forEach((key, i) => { if (previous[i] === undefined) delete process.env[key]; else process.env[key] = previous[i]; });
    rmSync(dir, { recursive: true });
  }
});
