-- Keep unverified legacy profiles untouched. Never claim them by display name.
CREATE TABLE IF NOT EXISTS player_identity_profile (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  identity_key VARCHAR(100) NOT NULL,
  username VARCHAR(100) NOT NULL,
  world_id VARCHAR(64) NOT NULL,
  health INT NOT NULL DEFAULT 100,
  max_health INT NOT NULL DEFAULT 100,
  stamina INT NOT NULL DEFAULT 100,
  max_stamina INT NOT NULL DEFAULT 100,
  hunger INT NOT NULL DEFAULT 100,
  max_hunger INT NOT NULL DEFAULT 100,
  level INT NOT NULL DEFAULT 1,
  experience BIGINT NOT NULL DEFAULT 0,
  pos_x DOUBLE NOT NULL DEFAULT 0,
  pos_y DOUBLE NOT NULL DEFAULT 0,
  pos_z DOUBLE NOT NULL DEFAULT 0,
  rot_x DOUBLE NOT NULL DEFAULT 0,
  rot_y DOUBLE NOT NULL DEFAULT 0,
  rot_z DOUBLE NOT NULL DEFAULT 0,
  map_id VARCHAR(64) NOT NULL DEFAULT 'exterior',
  role_id VARCHAR(64) NULL,
  stats_json JSON NULL,
  inventory_json JSON NULL,
  housing_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_player_identity_key (identity_key),
  KEY idx_player_identity_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
